apiVersion: apps/vi
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: {{ .Values.replicas }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.service.labels.app }}
    spec:
      containers:
      - name: {{ .Values.service.labels.app }}
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: {{ .Values.env.host }}
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.env.valueFrom.configMapKeyRef.name }}
              key: {{ .Values.env.valueFrom.configMapKeyRef.key }}
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-conf
              key: redis-port
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: redis-conf
              key: redis-pass
